server:
  port: 8084

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:h2:mem:employeedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/enterprise-hr-realm

# Custom property for our multi-tenancy logic
multi-tenancy:
  claim-name: organization